namespace Reginald.Tests
{
    using Reginald.Data.DisplayItems;
    using Reginald.Data.Keywords;
    using Xunit;

    public static class TimerKeywordTests
    {
        [Fact]
        public static void EnterDown_WhenCompletionIsNotNullAndTimeIsGreaterThanZero_TimerShouldBeAdded()
        {
            TimerKeyword timerKeyword = new();
            timerKeyword.Completion = " ";
            timerKeyword.Time = 1;
            timerKeyword.EnterKeyDown();
            Assert.True(TimerResult.GetTimers("timers").Count > 0);
        }

        [Theory]
        [InlineData("1h Take out trash")]
        [InlineData("1h 1m Take out trash")]
        [InlineData("1h 1min Take out trash")]
        [InlineData("1h 1mins Take out trash")]
        [InlineData("1h 1minute Take out trash")]
        [InlineData("1h 1minutes Take out trash")]
        [InlineData("1h 1 m Take out trash")]
        [InlineData("1h 1 min Take out trash")]
        [InlineData("1h 1 mins Take out trash")]
        [InlineData("1h 1 minute Take out trash")]
        [InlineData("1h 1 minutes Take out trash")]
        [InlineData("1h 1m 1s Take out trash")]
        [InlineData("1h 1m 1sec Take out trash")]
        [InlineData("1h 1m 1secs Take out trash")]
        [InlineData("1h 1m 1second Take out trash")]
        [InlineData("1h 1m 1seconds Take out trash")]
        [InlineData("1h 1m 1 s Take out trash")]
        [InlineData("1h 1m 1 sec Take out trash")]
        [InlineData("1h 1m 1 secs Take out trash")]
        [InlineData("1h 1m 1 second Take out trash")]
        [InlineData("1h 1m 1 seconds Take out trash")]
        [InlineData("1h 1 min 1s Take out trash")]
        [InlineData("1h 1 min 1sec Take out trash")]
        [InlineData("1h 1 min 1secs Take out trash")]
        [InlineData("1h 1 min 1second Take out trash")]
        [InlineData("1h 1 min 1seconds Take out trash")]
        [InlineData("1h 1 min 1 s Take out trash")]
        [InlineData("1h 1 min 1 sec Take out trash")]
        [InlineData("1h 1 min 1 secs Take out trash")]
        [InlineData("1h 1 min 1 second Take out trash")]
        [InlineData("1h 1 min 1 seconds Take out trash")]
        [InlineData("1h 1 mins 1s Take out trash")]
        [InlineData("1h 1 mins 1sec Take out trash")]
        [InlineData("1h 1 mins 1secs Take out trash")]
        [InlineData("1h 1 mins 1second Take out trash")]
        [InlineData("1h 1 mins 1seconds Take out trash")]
        [InlineData("1h 1 mins 1 s Take out trash")]
        [InlineData("1h 1 mins 1 sec Take out trash")]
        [InlineData("1h 1 mins 1 secs Take out trash")]
        [InlineData("1h 1 mins 1 second Take out trash")]
        [InlineData("1h 1 mins 1 seconds Take out trash")]
        [InlineData("1h 1 minute 1s Take out trash")]
        [InlineData("1h 1 minute 1sec Take out trash")]
        [InlineData("1h 1 minute 1secs Take out trash")]
        [InlineData("1h 1 minute 1second Take out trash")]
        [InlineData("1h 1 minute 1seconds Take out trash")]
        [InlineData("1h 1 minute 1 s Take out trash")]
        [InlineData("1h 1 minute 1 sec Take out trash")]
        [InlineData("1h 1 minute 1 secs Take out trash")]
        [InlineData("1h 1 minute 1 second Take out trash")]
        [InlineData("1h 1 minute 1 seconds Take out trash")]
        [InlineData("1h 1 minutes 1s Take out trash")]
        [InlineData("1h 1 minutes 1sec Take out trash")]
        [InlineData("1h 1 minutes 1secs Take out trash")]
        [InlineData("1h 1 minutes 1second Take out trash")]
        [InlineData("1h 1 minutes 1seconds Take out trash")]
        [InlineData("1h 1 minutes 1 s Take out trash")]
        [InlineData("1h 1 minutes 1 sec Take out trash")]
        [InlineData("1h 1 minutes 1 secs Take out trash")]
        [InlineData("1h 1 minutes 1 second Take out trash")]
        [InlineData("1h 1 minutes 1 seconds Take out trash")]

        [InlineData("1hr Take out trash")]
        [InlineData("1hr 1m Take out trash")]
        [InlineData("1hr 1min Take out trash")]
        [InlineData("1hr 1mins Take out trash")]
        [InlineData("1hr 1minute Take out trash")]
        [InlineData("1hr 1minutes Take out trash")]
        [InlineData("1hr 1 m Take out trash")]
        [InlineData("1hr 1 min Take out trash")]
        [InlineData("1hr 1 mins Take out trash")]
        [InlineData("1hr 1 minute Take out trash")]
        [InlineData("1hr 1 minutes Take out trash")]
        [InlineData("1hr 1m 1s Take out trash")]
        [InlineData("1hr 1m 1sec Take out trash")]
        [InlineData("1hr 1m 1secs Take out trash")]
        [InlineData("1hr 1m 1second Take out trash")]
        [InlineData("1hr 1m 1seconds Take out trash")]
        [InlineData("1hr 1m 1 s Take out trash")]
        [InlineData("1hr 1m 1 sec Take out trash")]
        [InlineData("1hr 1m 1 secs Take out trash")]
        [InlineData("1hr 1m 1 second Take out trash")]
        [InlineData("1hr 1m 1 seconds Take out trash")]
        [InlineData("1hr 1 min 1s Take out trash")]
        [InlineData("1hr 1 min 1sec Take out trash")]
        [InlineData("1hr 1 min 1secs Take out trash")]
        [InlineData("1hr 1 min 1second Take out trash")]
        [InlineData("1hr 1 min 1seconds Take out trash")]
        [InlineData("1hr 1 min 1 s Take out trash")]
        [InlineData("1hr 1 min 1 sec Take out trash")]
        [InlineData("1hr 1 min 1 secs Take out trash")]
        [InlineData("1hr 1 min 1 second Take out trash")]
        [InlineData("1hr 1 min 1 seconds Take out trash")]
        [InlineData("1hr 1 mins 1s Take out trash")]
        [InlineData("1hr 1 mins 1sec Take out trash")]
        [InlineData("1hr 1 mins 1secs Take out trash")]
        [InlineData("1hr 1 mins 1second Take out trash")]
        [InlineData("1hr 1 mins 1seconds Take out trash")]
        [InlineData("1hr 1 mins 1 s Take out trash")]
        [InlineData("1hr 1 mins 1 sec Take out trash")]
        [InlineData("1hr 1 mins 1 secs Take out trash")]
        [InlineData("1hr 1 mins 1 second Take out trash")]
        [InlineData("1hr 1 mins 1 seconds Take out trash")]
        [InlineData("1hr 1 minute 1s Take out trash")]
        [InlineData("1hr 1 minute 1sec Take out trash")]
        [InlineData("1hr 1 minute 1secs Take out trash")]
        [InlineData("1hr 1 minute 1second Take out trash")]
        [InlineData("1hr 1 minute 1seconds Take out trash")]
        [InlineData("1hr 1 minute 1 s Take out trash")]
        [InlineData("1hr 1 minute 1 sec Take out trash")]
        [InlineData("1hr 1 minute 1 secs Take out trash")]
        [InlineData("1hr 1 minute 1 second Take out trash")]
        [InlineData("1hr 1 minute 1 seconds Take out trash")]
        [InlineData("1hr 1 minutes 1s Take out trash")]
        [InlineData("1hr 1 minutes 1sec Take out trash")]
        [InlineData("1hr 1 minutes 1secs Take out trash")]
        [InlineData("1hr 1 minutes 1second Take out trash")]
        [InlineData("1hr 1 minutes 1seconds Take out trash")]
        [InlineData("1hr 1 minutes 1 s Take out trash")]
        [InlineData("1hr 1 minutes 1 sec Take out trash")]
        [InlineData("1hr 1 minutes 1 secs Take out trash")]
        [InlineData("1hr 1 minutes 1 second Take out trash")]
        [InlineData("1hr 1 minutes 1 seconds Take out trash")]

        [InlineData("1hrs Take out trash")]
        [InlineData("1hrs 1m Take out trash")]
        [InlineData("1hrs 1min Take out trash")]
        [InlineData("1hrs 1mins Take out trash")]
        [InlineData("1hrs 1minute Take out trash")]
        [InlineData("1hrs 1minutes Take out trash")]
        [InlineData("1hrs 1 m Take out trash")]
        [InlineData("1hrs 1 min Take out trash")]
        [InlineData("1hrs 1 mins Take out trash")]
        [InlineData("1hrs 1 minute Take out trash")]
        [InlineData("1hrs 1 minutes Take out trash")]
        [InlineData("1hrs 1m 1s Take out trash")]
        [InlineData("1hrs 1m 1sec Take out trash")]
        [InlineData("1hrs 1m 1secs Take out trash")]
        [InlineData("1hrs 1m 1second Take out trash")]
        [InlineData("1hrs 1m 1seconds Take out trash")]
        [InlineData("1hrs 1m 1 s Take out trash")]
        [InlineData("1hrs 1m 1 sec Take out trash")]
        [InlineData("1hrs 1m 1 secs Take out trash")]
        [InlineData("1hrs 1m 1 second Take out trash")]
        [InlineData("1hrs 1m 1 seconds Take out trash")]
        [InlineData("1hrs 1 min 1s Take out trash")]
        [InlineData("1hrs 1 min 1sec Take out trash")]
        [InlineData("1hrs 1 min 1secs Take out trash")]
        [InlineData("1hrs 1 min 1second Take out trash")]
        [InlineData("1hrs 1 min 1seconds Take out trash")]
        [InlineData("1hrs 1 min 1 s Take out trash")]
        [InlineData("1hrs 1 min 1 sec Take out trash")]
        [InlineData("1hrs 1 min 1 secs Take out trash")]
        [InlineData("1hrs 1 min 1 second Take out trash")]
        [InlineData("1hrs 1 min 1 seconds Take out trash")]
        [InlineData("1hrs 1 mins 1s Take out trash")]
        [InlineData("1hrs 1 mins 1sec Take out trash")]
        [InlineData("1hrs 1 mins 1secs Take out trash")]
        [InlineData("1hrs 1 mins 1second Take out trash")]
        [InlineData("1hrs 1 mins 1seconds Take out trash")]
        [InlineData("1hrs 1 mins 1 s Take out trash")]
        [InlineData("1hrs 1 mins 1 sec Take out trash")]
        [InlineData("1hrs 1 mins 1 secs Take out trash")]
        [InlineData("1hrs 1 mins 1 second Take out trash")]
        [InlineData("1hrs 1 mins 1 seconds Take out trash")]
        [InlineData("1hrs 1 minute 1s Take out trash")]
        [InlineData("1hrs 1 minute 1sec Take out trash")]
        [InlineData("1hrs 1 minute 1secs Take out trash")]
        [InlineData("1hrs 1 minute 1second Take out trash")]
        [InlineData("1hrs 1 minute 1seconds Take out trash")]
        [InlineData("1hrs 1 minute 1 s Take out trash")]
        [InlineData("1hrs 1 minute 1 sec Take out trash")]
        [InlineData("1hrs 1 minute 1 secs Take out trash")]
        [InlineData("1hrs 1 minute 1 second Take out trash")]
        [InlineData("1hrs 1 minute 1 seconds Take out trash")]
        [InlineData("1hrs 1 minutes 1s Take out trash")]
        [InlineData("1hrs 1 minutes 1sec Take out trash")]
        [InlineData("1hrs 1 minutes 1secs Take out trash")]
        [InlineData("1hrs 1 minutes 1second Take out trash")]
        [InlineData("1hrs 1 minutes 1seconds Take out trash")]
        [InlineData("1hrs 1 minutes 1 s Take out trash")]
        [InlineData("1hrs 1 minutes 1 sec Take out trash")]
        [InlineData("1hrs 1 minutes 1 secs Take out trash")]
        [InlineData("1hrs 1 minutes 1 second Take out trash")]
        [InlineData("1hrs 1 minutes 1 seconds Take out trash")]

        [InlineData("1hour Take out trash")]
        [InlineData("1hour 1m Take out trash")]
        [InlineData("1hour 1min Take out trash")]
        [InlineData("1hour 1mins Take out trash")]
        [InlineData("1hour 1minute Take out trash")]
        [InlineData("1hour 1minutes Take out trash")]
        [InlineData("1hour 1 m Take out trash")]
        [InlineData("1hour 1 min Take out trash")]
        [InlineData("1hour 1 mins Take out trash")]
        [InlineData("1hour 1 minute Take out trash")]
        [InlineData("1hour 1 minutes Take out trash")]
        [InlineData("1hour 1m 1s Take out trash")]
        [InlineData("1hour 1m 1sec Take out trash")]
        [InlineData("1hour 1m 1secs Take out trash")]
        [InlineData("1hour 1m 1second Take out trash")]
        [InlineData("1hour 1m 1seconds Take out trash")]
        [InlineData("1hour 1m 1 s Take out trash")]
        [InlineData("1hour 1m 1 sec Take out trash")]
        [InlineData("1hour 1m 1 secs Take out trash")]
        [InlineData("1hour 1m 1 second Take out trash")]
        [InlineData("1hour 1m 1 seconds Take out trash")]
        [InlineData("1hour 1 min 1s Take out trash")]
        [InlineData("1hour 1 min 1sec Take out trash")]
        [InlineData("1hour 1 min 1secs Take out trash")]
        [InlineData("1hour 1 min 1second Take out trash")]
        [InlineData("1hour 1 min 1seconds Take out trash")]
        [InlineData("1hour 1 min 1 s Take out trash")]
        [InlineData("1hour 1 min 1 sec Take out trash")]
        [InlineData("1hour 1 min 1 secs Take out trash")]
        [InlineData("1hour 1 min 1 second Take out trash")]
        [InlineData("1hour 1 min 1 seconds Take out trash")]
        [InlineData("1hour 1 mins 1s Take out trash")]
        [InlineData("1hour 1 mins 1sec Take out trash")]
        [InlineData("1hour 1 mins 1secs Take out trash")]
        [InlineData("1hour 1 mins 1second Take out trash")]
        [InlineData("1hour 1 mins 1seconds Take out trash")]
        [InlineData("1hour 1 mins 1 s Take out trash")]
        [InlineData("1hour 1 mins 1 sec Take out trash")]
        [InlineData("1hour 1 mins 1 secs Take out trash")]
        [InlineData("1hour 1 mins 1 second Take out trash")]
        [InlineData("1hour 1 mins 1 seconds Take out trash")]
        [InlineData("1hour 1 minute 1s Take out trash")]
        [InlineData("1hour 1 minute 1sec Take out trash")]
        [InlineData("1hour 1 minute 1secs Take out trash")]
        [InlineData("1hour 1 minute 1second Take out trash")]
        [InlineData("1hour 1 minute 1seconds Take out trash")]
        [InlineData("1hour 1 minute 1 s Take out trash")]
        [InlineData("1hour 1 minute 1 sec Take out trash")]
        [InlineData("1hour 1 minute 1 secs Take out trash")]
        [InlineData("1hour 1 minute 1 second Take out trash")]
        [InlineData("1hour 1 minute 1 seconds Take out trash")]
        [InlineData("1hour 1 minutes 1s Take out trash")]
        [InlineData("1hour 1 minutes 1sec Take out trash")]
        [InlineData("1hour 1 minutes 1secs Take out trash")]
        [InlineData("1hour 1 minutes 1second Take out trash")]
        [InlineData("1hour 1 minutes 1seconds Take out trash")]
        [InlineData("1hour 1 minutes 1 s Take out trash")]
        [InlineData("1hour 1 minutes 1 sec Take out trash")]
        [InlineData("1hour 1 minutes 1 secs Take out trash")]
        [InlineData("1hour 1 minutes 1 second Take out trash")]
        [InlineData("1hour 1 minutes 1 seconds Take out trash")]

        [InlineData("1hours Take out trash")]
        [InlineData("1hours 1m Take out trash")]
        [InlineData("1hours 1min Take out trash")]
        [InlineData("1hours 1mins Take out trash")]
        [InlineData("1hours 1minute Take out trash")]
        [InlineData("1hours 1minutes Take out trash")]
        [InlineData("1hours 1 m Take out trash")]
        [InlineData("1hours 1 min Take out trash")]
        [InlineData("1hours 1 mins Take out trash")]
        [InlineData("1hours 1 minute Take out trash")]
        [InlineData("1hours 1 minutes Take out trash")]
        [InlineData("1hours 1m 1s Take out trash")]
        [InlineData("1hours 1m 1sec Take out trash")]
        [InlineData("1hours 1m 1secs Take out trash")]
        [InlineData("1hours 1m 1second Take out trash")]
        [InlineData("1hours 1m 1seconds Take out trash")]
        [InlineData("1hours 1m 1 s Take out trash")]
        [InlineData("1hours 1m 1 sec Take out trash")]
        [InlineData("1hours 1m 1 secs Take out trash")]
        [InlineData("1hours 1m 1 second Take out trash")]
        [InlineData("1hours 1m 1 seconds Take out trash")]
        [InlineData("1hours 1 min 1s Take out trash")]
        [InlineData("1hours 1 min 1sec Take out trash")]
        [InlineData("1hours 1 min 1secs Take out trash")]
        [InlineData("1hours 1 min 1second Take out trash")]
        [InlineData("1hours 1 min 1seconds Take out trash")]
        [InlineData("1hours 1 min 1 s Take out trash")]
        [InlineData("1hours 1 min 1 sec Take out trash")]
        [InlineData("1hours 1 min 1 secs Take out trash")]
        [InlineData("1hours 1 min 1 second Take out trash")]
        [InlineData("1hours 1 min 1 seconds Take out trash")]
        [InlineData("1hours 1 mins 1s Take out trash")]
        [InlineData("1hours 1 mins 1sec Take out trash")]
        [InlineData("1hours 1 mins 1secs Take out trash")]
        [InlineData("1hours 1 mins 1second Take out trash")]
        [InlineData("1hours 1 mins 1seconds Take out trash")]
        [InlineData("1hours 1 mins 1 s Take out trash")]
        [InlineData("1hours 1 mins 1 sec Take out trash")]
        [InlineData("1hours 1 mins 1 secs Take out trash")]
        [InlineData("1hours 1 mins 1 second Take out trash")]
        [InlineData("1hours 1 mins 1 seconds Take out trash")]
        [InlineData("1hours 1 minute 1s Take out trash")]
        [InlineData("1hours 1 minute 1sec Take out trash")]
        [InlineData("1hours 1 minute 1secs Take out trash")]
        [InlineData("1hours 1 minute 1second Take out trash")]
        [InlineData("1hours 1 minute 1seconds Take out trash")]
        [InlineData("1hours 1 minute 1 s Take out trash")]
        [InlineData("1hours 1 minute 1 sec Take out trash")]
        [InlineData("1hours 1 minute 1 secs Take out trash")]
        [InlineData("1hours 1 minute 1 second Take out trash")]
        [InlineData("1hours 1 minute 1 seconds Take out trash")]
        [InlineData("1hours 1 minutes 1s Take out trash")]
        [InlineData("1hours 1 minutes 1sec Take out trash")]
        [InlineData("1hours 1 minutes 1secs Take out trash")]
        [InlineData("1hours 1 minutes 1second Take out trash")]
        [InlineData("1hours 1 minutes 1seconds Take out trash")]
        [InlineData("1hours 1 minutes 1 s Take out trash")]
        [InlineData("1hours 1 minutes 1 sec Take out trash")]
        [InlineData("1hours 1 minutes 1 secs Take out trash")]
        [InlineData("1hours 1 minutes 1 second Take out trash")]
        [InlineData("1hours 1 minutes 1 seconds Take out trash")]

        [InlineData("1 h Take out trash")]
        [InlineData("1 h 1m Take out trash")]
        [InlineData("1 h 1min Take out trash")]
        [InlineData("1 h 1mins Take out trash")]
        [InlineData("1 h 1minute Take out trash")]
        [InlineData("1 h 1minutes Take out trash")]
        [InlineData("1 h 1 m Take out trash")]
        [InlineData("1 h 1 min Take out trash")]
        [InlineData("1 h 1 mins Take out trash")]
        [InlineData("1 h 1 minute Take out trash")]
        [InlineData("1 h 1 minutes Take out trash")]
        [InlineData("1 h 1m 1s Take out trash")]
        [InlineData("1 h 1m 1sec Take out trash")]
        [InlineData("1 h 1m 1secs Take out trash")]
        [InlineData("1 h 1m 1second Take out trash")]
        [InlineData("1 h 1m 1seconds Take out trash")]
        [InlineData("1 h 1m 1 s Take out trash")]
        [InlineData("1 h 1m 1 sec Take out trash")]
        [InlineData("1 h 1m 1 secs Take out trash")]
        [InlineData("1 h 1m 1 second Take out trash")]
        [InlineData("1 h 1m 1 seconds Take out trash")]
        [InlineData("1 h 1 min 1s Take out trash")]
        [InlineData("1 h 1 min 1sec Take out trash")]
        [InlineData("1 h 1 min 1secs Take out trash")]
        [InlineData("1 h 1 min 1second Take out trash")]
        [InlineData("1 h 1 min 1seconds Take out trash")]
        [InlineData("1 h 1 min 1 s Take out trash")]
        [InlineData("1 h 1 min 1 sec Take out trash")]
        [InlineData("1 h 1 min 1 secs Take out trash")]
        [InlineData("1 h 1 min 1 second Take out trash")]
        [InlineData("1 h 1 min 1 seconds Take out trash")]
        [InlineData("1 h 1 mins 1s Take out trash")]
        [InlineData("1 h 1 mins 1sec Take out trash")]
        [InlineData("1 h 1 mins 1secs Take out trash")]
        [InlineData("1 h 1 mins 1second Take out trash")]
        [InlineData("1 h 1 mins 1seconds Take out trash")]
        [InlineData("1 h 1 mins 1 s Take out trash")]
        [InlineData("1 h 1 mins 1 sec Take out trash")]
        [InlineData("1 h 1 mins 1 secs Take out trash")]
        [InlineData("1 h 1 mins 1 second Take out trash")]
        [InlineData("1 h 1 mins 1 seconds Take out trash")]
        [InlineData("1 h 1 minute 1s Take out trash")]
        [InlineData("1 h 1 minute 1sec Take out trash")]
        [InlineData("1 h 1 minute 1secs Take out trash")]
        [InlineData("1 h 1 minute 1second Take out trash")]
        [InlineData("1 h 1 minute 1seconds Take out trash")]
        [InlineData("1 h 1 minute 1 s Take out trash")]
        [InlineData("1 h 1 minute 1 sec Take out trash")]
        [InlineData("1 h 1 minute 1 secs Take out trash")]
        [InlineData("1 h 1 minute 1 second Take out trash")]
        [InlineData("1 h 1 minute 1 seconds Take out trash")]
        [InlineData("1 h 1 minutes 1s Take out trash")]
        [InlineData("1 h 1 minutes 1sec Take out trash")]
        [InlineData("1 h 1 minutes 1secs Take out trash")]
        [InlineData("1 h 1 minutes 1second Take out trash")]
        [InlineData("1 h 1 minutes 1seconds Take out trash")]
        [InlineData("1 h 1 minutes 1 s Take out trash")]
        [InlineData("1 h 1 minutes 1 sec Take out trash")]
        [InlineData("1 h 1 minutes 1 secs Take out trash")]
        [InlineData("1 h 1 minutes 1 second Take out trash")]
        [InlineData("1 h 1 minutes 1 seconds Take out trash")]

        [InlineData("1 hr Take out trash")]
        [InlineData("1 hr 1m Take out trash")]
        [InlineData("1 hr 1min Take out trash")]
        [InlineData("1 hr 1mins Take out trash")]
        [InlineData("1 hr 1minute Take out trash")]
        [InlineData("1 hr 1minutes Take out trash")]
        [InlineData("1 hr 1 m Take out trash")]
        [InlineData("1 hr 1 min Take out trash")]
        [InlineData("1 hr 1 mins Take out trash")]
        [InlineData("1 hr 1 minute Take out trash")]
        [InlineData("1 hr 1 minutes Take out trash")]
        [InlineData("1 hr 1m 1s Take out trash")]
        [InlineData("1 hr 1m 1sec Take out trash")]
        [InlineData("1 hr 1m 1secs Take out trash")]
        [InlineData("1 hr 1m 1second Take out trash")]
        [InlineData("1 hr 1m 1seconds Take out trash")]
        [InlineData("1 hr 1m 1 s Take out trash")]
        [InlineData("1 hr 1m 1 sec Take out trash")]
        [InlineData("1 hr 1m 1 secs Take out trash")]
        [InlineData("1 hr 1m 1 second Take out trash")]
        [InlineData("1 hr 1m 1 seconds Take out trash")]
        [InlineData("1 hr 1 min 1s Take out trash")]
        [InlineData("1 hr 1 min 1sec Take out trash")]
        [InlineData("1 hr 1 min 1secs Take out trash")]
        [InlineData("1 hr 1 min 1second Take out trash")]
        [InlineData("1 hr 1 min 1seconds Take out trash")]
        [InlineData("1 hr 1 min 1 s Take out trash")]
        [InlineData("1 hr 1 min 1 sec Take out trash")]
        [InlineData("1 hr 1 min 1 secs Take out trash")]
        [InlineData("1 hr 1 min 1 second Take out trash")]
        [InlineData("1 hr 1 min 1 seconds Take out trash")]
        [InlineData("1 hr 1 mins 1s Take out trash")]
        [InlineData("1 hr 1 mins 1sec Take out trash")]
        [InlineData("1 hr 1 mins 1secs Take out trash")]
        [InlineData("1 hr 1 mins 1second Take out trash")]
        [InlineData("1 hr 1 mins 1seconds Take out trash")]
        [InlineData("1 hr 1 mins 1 s Take out trash")]
        [InlineData("1 hr 1 mins 1 sec Take out trash")]
        [InlineData("1 hr 1 mins 1 secs Take out trash")]
        [InlineData("1 hr 1 mins 1 second Take out trash")]
        [InlineData("1 hr 1 mins 1 seconds Take out trash")]
        [InlineData("1 hr 1 minute 1s Take out trash")]
        [InlineData("1 hr 1 minute 1sec Take out trash")]
        [InlineData("1 hr 1 minute 1secs Take out trash")]
        [InlineData("1 hr 1 minute 1second Take out trash")]
        [InlineData("1 hr 1 minute 1seconds Take out trash")]
        [InlineData("1 hr 1 minute 1 s Take out trash")]
        [InlineData("1 hr 1 minute 1 sec Take out trash")]
        [InlineData("1 hr 1 minute 1 secs Take out trash")]
        [InlineData("1 hr 1 minute 1 second Take out trash")]
        [InlineData("1 hr 1 minute 1 seconds Take out trash")]
        [InlineData("1 hr 1 minutes 1s Take out trash")]
        [InlineData("1 hr 1 minutes 1sec Take out trash")]
        [InlineData("1 hr 1 minutes 1secs Take out trash")]
        [InlineData("1 hr 1 minutes 1second Take out trash")]
        [InlineData("1 hr 1 minutes 1seconds Take out trash")]
        [InlineData("1 hr 1 minutes 1 s Take out trash")]
        [InlineData("1 hr 1 minutes 1 sec Take out trash")]
        [InlineData("1 hr 1 minutes 1 secs Take out trash")]
        [InlineData("1 hr 1 minutes 1 second Take out trash")]
        [InlineData("1 hr 1 minutes 1 seconds Take out trash")]

        [InlineData("1 hrs Take out trash")]
        [InlineData("1 hrs 1m Take out trash")]
        [InlineData("1 hrs 1min Take out trash")]
        [InlineData("1 hrs 1mins Take out trash")]
        [InlineData("1 hrs 1minute Take out trash")]
        [InlineData("1 hrs 1minutes Take out trash")]
        [InlineData("1 hrs 1 m Take out trash")]
        [InlineData("1 hrs 1 min Take out trash")]
        [InlineData("1 hrs 1 mins Take out trash")]
        [InlineData("1 hrs 1 minute Take out trash")]
        [InlineData("1 hrs 1 minutes Take out trash")]
        [InlineData("1 hrs 1m 1s Take out trash")]
        [InlineData("1 hrs 1m 1sec Take out trash")]
        [InlineData("1 hrs 1m 1secs Take out trash")]
        [InlineData("1 hrs 1m 1second Take out trash")]
        [InlineData("1 hrs 1m 1seconds Take out trash")]
        [InlineData("1 hrs 1m 1 s Take out trash")]
        [InlineData("1 hrs 1m 1 sec Take out trash")]
        [InlineData("1 hrs 1m 1 secs Take out trash")]
        [InlineData("1 hrs 1m 1 second Take out trash")]
        [InlineData("1 hrs 1m 1 seconds Take out trash")]
        [InlineData("1 hrs 1 min 1s Take out trash")]
        [InlineData("1 hrs 1 min 1sec Take out trash")]
        [InlineData("1 hrs 1 min 1secs Take out trash")]
        [InlineData("1 hrs 1 min 1second Take out trash")]
        [InlineData("1 hrs 1 min 1seconds Take out trash")]
        [InlineData("1 hrs 1 min 1 s Take out trash")]
        [InlineData("1 hrs 1 min 1 sec Take out trash")]
        [InlineData("1 hrs 1 min 1 secs Take out trash")]
        [InlineData("1 hrs 1 min 1 second Take out trash")]
        [InlineData("1 hrs 1 min 1 seconds Take out trash")]
        [InlineData("1 hrs 1 mins 1s Take out trash")]
        [InlineData("1 hrs 1 mins 1sec Take out trash")]
        [InlineData("1 hrs 1 mins 1secs Take out trash")]
        [InlineData("1 hrs 1 mins 1second Take out trash")]
        [InlineData("1 hrs 1 mins 1seconds Take out trash")]
        [InlineData("1 hrs 1 mins 1 s Take out trash")]
        [InlineData("1 hrs 1 mins 1 sec Take out trash")]
        [InlineData("1 hrs 1 mins 1 secs Take out trash")]
        [InlineData("1 hrs 1 mins 1 second Take out trash")]
        [InlineData("1 hrs 1 mins 1 seconds Take out trash")]
        [InlineData("1 hrs 1 minute 1s Take out trash")]
        [InlineData("1 hrs 1 minute 1sec Take out trash")]
        [InlineData("1 hrs 1 minute 1secs Take out trash")]
        [InlineData("1 hrs 1 minute 1second Take out trash")]
        [InlineData("1 hrs 1 minute 1seconds Take out trash")]
        [InlineData("1 hrs 1 minute 1 s Take out trash")]
        [InlineData("1 hrs 1 minute 1 sec Take out trash")]
        [InlineData("1 hrs 1 minute 1 secs Take out trash")]
        [InlineData("1 hrs 1 minute 1 second Take out trash")]
        [InlineData("1 hrs 1 minute 1 seconds Take out trash")]
        [InlineData("1 hrs 1 minutes 1s Take out trash")]
        [InlineData("1 hrs 1 minutes 1sec Take out trash")]
        [InlineData("1 hrs 1 minutes 1secs Take out trash")]
        [InlineData("1 hrs 1 minutes 1second Take out trash")]
        [InlineData("1 hrs 1 minutes 1seconds Take out trash")]
        [InlineData("1 hrs 1 minutes 1 s Take out trash")]
        [InlineData("1 hrs 1 minutes 1 sec Take out trash")]
        [InlineData("1 hrs 1 minutes 1 secs Take out trash")]
        [InlineData("1 hrs 1 minutes 1 second Take out trash")]
        [InlineData("1 hrs 1 minutes 1 seconds Take out trash")]

        [InlineData("1 hour Take out trash")]
        [InlineData("1 hour 1m Take out trash")]
        [InlineData("1 hour 1min Take out trash")]
        [InlineData("1 hour 1mins Take out trash")]
        [InlineData("1 hour 1minute Take out trash")]
        [InlineData("1 hour 1minutes Take out trash")]
        [InlineData("1 hour 1 m Take out trash")]
        [InlineData("1 hour 1 min Take out trash")]
        [InlineData("1 hour 1 mins Take out trash")]
        [InlineData("1 hour 1 minute Take out trash")]
        [InlineData("1 hour 1 minutes Take out trash")]
        [InlineData("1 hour 1m 1s Take out trash")]
        [InlineData("1 hour 1m 1sec Take out trash")]
        [InlineData("1 hour 1m 1secs Take out trash")]
        [InlineData("1 hour 1m 1second Take out trash")]
        [InlineData("1 hour 1m 1seconds Take out trash")]
        [InlineData("1 hour 1m 1 s Take out trash")]
        [InlineData("1 hour 1m 1 sec Take out trash")]
        [InlineData("1 hour 1m 1 secs Take out trash")]
        [InlineData("1 hour 1m 1 second Take out trash")]
        [InlineData("1 hour 1m 1 seconds Take out trash")]
        [InlineData("1 hour 1 min 1s Take out trash")]
        [InlineData("1 hour 1 min 1sec Take out trash")]
        [InlineData("1 hour 1 min 1secs Take out trash")]
        [InlineData("1 hour 1 min 1second Take out trash")]
        [InlineData("1 hour 1 min 1seconds Take out trash")]
        [InlineData("1 hour 1 min 1 s Take out trash")]
        [InlineData("1 hour 1 min 1 sec Take out trash")]
        [InlineData("1 hour 1 min 1 secs Take out trash")]
        [InlineData("1 hour 1 min 1 second Take out trash")]
        [InlineData("1 hour 1 min 1 seconds Take out trash")]
        [InlineData("1 hour 1 mins 1s Take out trash")]
        [InlineData("1 hour 1 mins 1sec Take out trash")]
        [InlineData("1 hour 1 mins 1secs Take out trash")]
        [InlineData("1 hour 1 mins 1second Take out trash")]
        [InlineData("1 hour 1 mins 1seconds Take out trash")]
        [InlineData("1 hour 1 mins 1 s Take out trash")]
        [InlineData("1 hour 1 mins 1 sec Take out trash")]
        [InlineData("1 hour 1 mins 1 secs Take out trash")]
        [InlineData("1 hour 1 mins 1 second Take out trash")]
        [InlineData("1 hour 1 mins 1 seconds Take out trash")]
        [InlineData("1 hour 1 minute 1s Take out trash")]
        [InlineData("1 hour 1 minute 1sec Take out trash")]
        [InlineData("1 hour 1 minute 1secs Take out trash")]
        [InlineData("1 hour 1 minute 1second Take out trash")]
        [InlineData("1 hour 1 minute 1seconds Take out trash")]
        [InlineData("1 hour 1 minute 1 s Take out trash")]
        [InlineData("1 hour 1 minute 1 sec Take out trash")]
        [InlineData("1 hour 1 minute 1 secs Take out trash")]
        [InlineData("1 hour 1 minute 1 second Take out trash")]
        [InlineData("1 hour 1 minute 1 seconds Take out trash")]
        [InlineData("1 hour 1 minutes 1s Take out trash")]
        [InlineData("1 hour 1 minutes 1sec Take out trash")]
        [InlineData("1 hour 1 minutes 1secs Take out trash")]
        [InlineData("1 hour 1 minutes 1second Take out trash")]
        [InlineData("1 hour 1 minutes 1seconds Take out trash")]
        [InlineData("1 hour 1 minutes 1 s Take out trash")]
        [InlineData("1 hour 1 minutes 1 sec Take out trash")]
        [InlineData("1 hour 1 minutes 1 secs Take out trash")]
        [InlineData("1 hour 1 minutes 1 second Take out trash")]
        [InlineData("1 hour 1 minutes 1 seconds Take out trash")]

        [InlineData("1 hours Take out trash")]
        [InlineData("1 hours 1m Take out trash")]
        [InlineData("1 hours 1min Take out trash")]
        [InlineData("1 hours 1mins Take out trash")]
        [InlineData("1 hours 1minute Take out trash")]
        [InlineData("1 hours 1minutes Take out trash")]
        [InlineData("1 hours 1 m Take out trash")]
        [InlineData("1 hours 1 min Take out trash")]
        [InlineData("1 hours 1 mins Take out trash")]
        [InlineData("1 hours 1 minute Take out trash")]
        [InlineData("1 hours 1 minutes Take out trash")]
        [InlineData("1 hours 1m 1s Take out trash")]
        [InlineData("1 hours 1m 1sec Take out trash")]
        [InlineData("1 hours 1m 1secs Take out trash")]
        [InlineData("1 hours 1m 1second Take out trash")]
        [InlineData("1 hours 1m 1seconds Take out trash")]
        [InlineData("1 hours 1m 1 s Take out trash")]
        [InlineData("1 hours 1m 1 sec Take out trash")]
        [InlineData("1 hours 1m 1 secs Take out trash")]
        [InlineData("1 hours 1m 1 second Take out trash")]
        [InlineData("1 hours 1m 1 seconds Take out trash")]
        [InlineData("1 hours 1 min 1s Take out trash")]
        [InlineData("1 hours 1 min 1sec Take out trash")]
        [InlineData("1 hours 1 min 1secs Take out trash")]
        [InlineData("1 hours 1 min 1second Take out trash")]
        [InlineData("1 hours 1 min 1seconds Take out trash")]
        [InlineData("1 hours 1 min 1 s Take out trash")]
        [InlineData("1 hours 1 min 1 sec Take out trash")]
        [InlineData("1 hours 1 min 1 secs Take out trash")]
        [InlineData("1 hours 1 min 1 second Take out trash")]
        [InlineData("1 hours 1 min 1 seconds Take out trash")]
        [InlineData("1 hours 1 mins 1s Take out trash")]
        [InlineData("1 hours 1 mins 1sec Take out trash")]
        [InlineData("1 hours 1 mins 1secs Take out trash")]
        [InlineData("1 hours 1 mins 1second Take out trash")]
        [InlineData("1 hours 1 mins 1seconds Take out trash")]
        [InlineData("1 hours 1 mins 1 s Take out trash")]
        [InlineData("1 hours 1 mins 1 sec Take out trash")]
        [InlineData("1 hours 1 mins 1 secs Take out trash")]
        [InlineData("1 hours 1 mins 1 second Take out trash")]
        [InlineData("1 hours 1 mins 1 seconds Take out trash")]
        [InlineData("1 hours 1 minute 1s Take out trash")]
        [InlineData("1 hours 1 minute 1sec Take out trash")]
        [InlineData("1 hours 1 minute 1secs Take out trash")]
        [InlineData("1 hours 1 minute 1second Take out trash")]
        [InlineData("1 hours 1 minute 1seconds Take out trash")]
        [InlineData("1 hours 1 minute 1 s Take out trash")]
        [InlineData("1 hours 1 minute 1 sec Take out trash")]
        [InlineData("1 hours 1 minute 1 secs Take out trash")]
        [InlineData("1 hours 1 minute 1 second Take out trash")]
        [InlineData("1 hours 1 minute 1 seconds Take out trash")]
        [InlineData("1 hours 1 minutes 1s Take out trash")]
        [InlineData("1 hours 1 minutes 1sec Take out trash")]
        [InlineData("1 hours 1 minutes 1secs Take out trash")]
        [InlineData("1 hours 1 minutes 1second Take out trash")]
        [InlineData("1 hours 1 minutes 1seconds Take out trash")]
        [InlineData("1 hours 1 minutes 1 s Take out trash")]
        [InlineData("1 hours 1 minutes 1 sec Take out trash")]
        [InlineData("1 hours 1 minutes 1 secs Take out trash")]
        [InlineData("1 hours 1 minutes 1 second Take out trash")]
        [InlineData("1 hours 1 minutes 1 seconds Take out trash")]

        [InlineData("1m Take out trash")]
        [InlineData("1min Take out trash")]
        [InlineData("1mins Take out trash")]
        [InlineData("1minute Take out trash")]
        [InlineData("1minutes Take out trash")]
        [InlineData("1 m Take out trash")]
        [InlineData("1 min Take out trash")]
        [InlineData("1 mins Take out trash")]
        [InlineData("1 minute Take out trash")]
        [InlineData("1 minutes Take out trash")]
        [InlineData("1m 1s Take out trash")]
        [InlineData("1m 1sec Take out trash")]
        [InlineData("1m 1secs Take out trash")]
        [InlineData("1m 1second Take out trash")]
        [InlineData("1m 1seconds Take out trash")]
        [InlineData("1m 1 s Take out trash")]
        [InlineData("1m 1 sec Take out trash")]
        [InlineData("1m 1 secs Take out trash")]
        [InlineData("1m 1 second Take out trash")]
        [InlineData("1m 1 seconds Take out trash")]
        [InlineData("1 min 1s Take out trash")]
        [InlineData("1 min 1sec Take out trash")]
        [InlineData("1 min 1secs Take out trash")]
        [InlineData("1 min 1second Take out trash")]
        [InlineData("1 min 1seconds Take out trash")]
        [InlineData("1 min 1 s Take out trash")]
        [InlineData("1 min 1 sec Take out trash")]
        [InlineData("1 min 1 secs Take out trash")]
        [InlineData("1 min 1 second Take out trash")]
        [InlineData("1 min 1 seconds Take out trash")]
        [InlineData("1 mins 1s Take out trash")]
        [InlineData("1 mins 1sec Take out trash")]
        [InlineData("1 mins 1secs Take out trash")]
        [InlineData("1 mins 1second Take out trash")]
        [InlineData("1 mins 1seconds Take out trash")]
        [InlineData("1 mins 1 s Take out trash")]
        [InlineData("1 mins 1 sec Take out trash")]
        [InlineData("1 mins 1 secs Take out trash")]
        [InlineData("1 mins 1 second Take out trash")]
        [InlineData("1 mins 1 seconds Take out trash")]
        [InlineData("1 minute 1s Take out trash")]
        [InlineData("1 minute 1sec Take out trash")]
        [InlineData("1 minute 1secs Take out trash")]
        [InlineData("1 minute 1second Take out trash")]
        [InlineData("1 minute 1seconds Take out trash")]
        [InlineData("1 minute 1 s Take out trash")]
        [InlineData("1 minute 1 sec Take out trash")]
        [InlineData("1 minute 1 secs Take out trash")]
        [InlineData("1 minute 1 second Take out trash")]
        [InlineData("1 minute 1 seconds Take out trash")]
        [InlineData("1 minutes 1s Take out trash")]
        [InlineData("1 minutes 1sec Take out trash")]
        [InlineData("1 minutes 1secs Take out trash")]
        [InlineData("1 minutes 1second Take out trash")]
        [InlineData("1 minutes 1seconds Take out trash")]
        [InlineData("1 minutes 1 s Take out trash")]
        [InlineData("1 minutes 1 sec Take out trash")]
        [InlineData("1 minutes 1 secs Take out trash")]
        [InlineData("1 minutes 1 second Take out trash")]
        [InlineData("1 minutes 1 seconds Take out trash")]

        [InlineData("1s Take out trash")]
        [InlineData("1sec Take out trash")]
        [InlineData("1secs Take out trash")]
        [InlineData("1second Take out trash")]
        [InlineData("1seconds Take out trash")]
        [InlineData("1 s Take out trash")]
        [InlineData("1 sec Take out trash")]
        [InlineData("1 secs Take out trash")]
        [InlineData("1 second Take out trash")]
        [InlineData("1 seconds Take out trash")]
        public static void TryParseTimeFromString_WhenGivenTimeRepresentation_ShouldReturnTrue(string input)
        {
            TimerKeyword timerKeyword = new();
            timerKeyword.Placeholder = "...";
            timerKeyword.Format = "In {0}: {1}";
            bool result = timerKeyword.TryParseTimeFromString(input);
            Assert.True(result);
        }

        [Theory]
        [InlineData("Take out trash 1h")]
        [InlineData("Take out trash 1m")]
        [InlineData("Take out trash 1s")]
        [InlineData(" 1 hr")]
        public static void TryParseTimeFromString_WhenGivenTimeRepresentation_ShouldReturnFalse(string input)
        {
            TimerKeyword timerKeyword = new();
            timerKeyword.Placeholder = "...";
            timerKeyword.Format = "In {0}: {1}";
            bool result = timerKeyword.TryParseTimeFromString(input);
            Assert.False(result);
        }

        [Theory]
        [InlineData("1 min Take out trash", 60000)]
        [InlineData("1 min Take out trash 5 min", 60000)]
        [InlineData("1 min 1s Take out trash 5 min", 61000)]
        [InlineData("1hr 1min 1s Take out trash", 3661000)]
        [InlineData("3 min Take out trash", 180000)]
        [InlineData("3 min Take out trash 5 min", 180000)]
        [InlineData("3 min 1s Take out trash 5 min", 181000)]
        [InlineData("3hr 1min 1s Take out trash", 10861000)]
        public static void TryParseTimeFromString_WhenGivenTimeRepresentation_ShouldProduceCorrectTime(string input, double expected)
        {
            TimerKeyword timerKeyword = new();
            timerKeyword.Placeholder = "...";
            timerKeyword.Format = "In {0}: {1}";
            _ = timerKeyword.TryParseTimeFromString(input);
            Assert.Equal(expected, timerKeyword.Time);
        }
    }
}
