name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'ext/**'
      - 'scripts/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'ext/**'
      - 'scripts/**'
      - '*.md'

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal